V18.09
UnitedPlanet/intrexx-sample-connector-api pull request #2
Opened 2018-11-28 15:20 UTC by up-philippfels

Update Doku & Fix GoogleDirveAdapter for new BL

2018-11-29 08:49 UTC, manr requested changes

2018-11-29 08:49 UTC, manr commented on src/main/java/de/uplanet/lucy/connectorapi/examples/google/drive/datagroup/GoogleDriveDataGroupService.java
> +	private String _extreactStringFieldValue(IConnectorRecord p_record, String p_fieldName)
Typo in method name.

2018-11-29 08:49 UTC, manr commented on src/main/java/de/uplanet/lucy/connectorapi/examples/google/drive/datagroup/GoogleDriveDataGroupService.java
> +		if (l_value instanceof String)
Please use `ValueHolderHelper.getStringFromVH(l_field.getValue())` instead of using instanceof.

2018-11-29 08:49 UTC, manr commented on build.gradle
> +version = '9.0.3'
Please change to 9.0.5.

2018-11-30 10:02 UTC, up-philippfels commented
Fix your pull request Issues

2018-11-30 10:06 UTC, up-philippfels commented
Fix your pull request Issues

2018-12-03 15:42 UTC, merged